// Al&Ni Studios - Ürün Veritabanı (Shopier Orijinal Verileri + Detaylı Açıklamalar)
// Bu dosya API'den otomatik güncellenir, manuel değişiklik yapmayınız

const products = [
    {
        id: 1,
        shopierProductId: "43908191",
        name: "Sevgililer Günü - Aşk Hikayemiz Timeline Defteri",
        price: 210,
        category: "sevgililer",
        shopierUrl: "https://www.shopier.com/alnigamestudios/43908191",
        badge: "Yeni",
        description: "Aşk hikayenizi zamansız bir timeline defterinde ölümsüzleştirin",
        fullDescription: "Aşk Hikayemiz Timeline Defteri ile birlikte ilişkinizin önemli anlarını kronolojik bir sırayla sunabilirsiniz. Tanışma, ilk buluşma, özel günler ve daha fazlası... Kişiye özel fotoğraflar ve mesajlarla özelleştirilebilir. Tüm düzenlemeleri sipariş notuna yazmanız yeterlidir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_44ac3f3aafe1e3b53f9c78b8cb5ed3a1.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 2,
        shopierProductId: "43045000",
        name: "Aşkım Döv Beni Döv",
        price: 160,
        category: "eglence",
        shopierUrl: "https://www.shopier.com/alnigamestudios/43045000",
        badge: "Popüler",
        description: "Eğlenceli ve interaktif dijital oyun deneyimi",
        fullDescription: "Punch Toy – Kişiselleştirilebilir Joker Paketleri. Eğlenceli bir oyun deneyimi sunan bu ürünle sevdiklerinize sürpriz yapabilirsiniz. Toy'u kendi tarzınıza göre özelleştirebilir, joker paketleri ekleyebilirsiniz. Sipariş notuna isteklerinizi yazmanız yeterlidir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_00f935f80f663367d8bb1a85d919acc4.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 3,
        shopierProductId: "41904134",
        name: "Netflix Temalı Anı Sarmalı",
        price: 300,
        category: "tema",
        shopierUrl: "https://www.shopier.com/alnigamestudios/41904134",
        badge: "Premium",
        description: "Normal ve Premium sürümler dahil - Netflix tarzı anı sunumu",
        fullDescription: "Netflix temalı anı sarmalı ürünümüz ile sevdiklerinizle paylaştığınız anıları Netflix tarzında sunabilirsiniz. Normal ve Premium sürümler mevcuttur. Fotoğraflarınız ve özel mesajlarınızla kişiselleştirilebilir. Tüm düzenlemeleri sipariş notuna yazmanız gerekmektedir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_4c69b9b25920713c30a4d6f5bafa5477.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 4,
        shopierProductId: "41903557",
        name: "Spotify Temalı Şarkı ve Fotoğraf Hikayesi",
        price: 250,
        category: "tema",
        shopierUrl: "https://www.shopier.com/alnigamestudios/41903557",
        badge: null,
        description: "Şarkılarınız ve fotoğraflarınızla özel bir hikaye oluşturun",
        fullDescription: "Uygulamamız içerisinde sevgilinizle sizi hatırlatan sizin için önemli olan fotoğraf ve şarkıların birbiriyle uyum içerisinde bulunduğu spotify temalı bir içerik bulunmaktadır. Dilediğiniz kadar şarkı ve fotoğraf eklemesi yapılabilmektedir. Uygulamamız içerisinde şarkı sözleri kısmı yerine güzel bir not bırakabilmeniz için bir alan yaratılmıştır. Tüm metinler, şarkılar ve fotoğraflar kişiye göre düzenlenebilmektedir. Gerekli düzenlemeleri sipariş notuna yazmanız gerekmektedir. Ürünü web sitesi olarak teslim almak için sipariş verirken web sitesi opsiyonunu eklemeniz gerekmektedir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_6127b2641842184decc1504d708d7dbc.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 5,
        shopierProductId: "41903211",
        name: "Özel Kasa Sürpriz",
        price: 100,
        category: "surpriz",
        shopierUrl: "https://www.shopier.com/alnigamestudios/41903211",
        badge: null,
        description: "Şifreli kasa içinde sürpriz hediye deneyimi",
        fullDescription: "Özel Kasa Sürpriz uygulamamızla dilediğiniz kişiye anlık harika bir heyecan yaratarak sürpriz yapabilirsiniz. İçerisindeki tüm metinler kişiye göre düzenlenebilir üretilmiştir. Gerekli düzenlemeleri sipariş notuna yazmanız yeterlidir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_20085e942302d2bb0e3a6e0c9fd3ee0c.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 6,
        shopierProductId: "41903017",
        name: "Dijital Kazı Kazan - Çoklu Seçim (Sihir Modlu)",
        price: 130,
        category: "eglence",
        shopierUrl: "https://www.shopier.com/alnigamestudios/41903017",
        badge: "Sihirli",
        description: "Birden fazla seçenekli sihirli kazı kazan deneyimi",
        fullDescription: "Dijital Kazı Kazan uygulamamızla dilediğiniz kişiye dilediğiniz şekilde heyecan yaratarak sürpriz yapabilirsiniz. Bütün seçenekler isteklerinize göre yeniden düzenlenebilir yapılmıştır. Uygulamamızda sihir modu seçeneği mevcuttur. Sihir modu açıldığı taktirde kullanıcı 3 seçenekten hangisini seçerse seçsin sizin istediğiniz sonuç gelir. Tüm özelleştirmeleri sipariş notuna yazmanız yeterlidir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_83a8fe8ded3b5ed340e94378ff0d9498.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 7,
        shopierProductId: "41902778",
        name: "Dijital Kazı Kazan",
        price: 100,
        category: "eglence",
        shopierUrl: "https://www.shopier.com/alnigamestudios/41902778",
        badge: null,
        description: "Klasik dijital kazı kazan sürprizi",
        fullDescription: "Dijital Kazı Kazan uygulamamızla dilediğiniz kişiye harika sürprizler yapabilirsiniz. Uygulamamız dilediğiniz gibi istediğiniz fotoğraflar ve metinlerle özelleştirilebilmektedir. Dilerseniz uygulamanız web sitesi olarak da verilebilmektedir. Belirtilen özelleştirmeleri sipariş notuna girmeniz yeterlidir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_ee2820452a36da6e4754c5e629cd8c20.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 8,
        shopierProductId: "41625102",
        name: "Kafe Menü Sistemi Standart",
        price: 260,
        category: "isletme",
        shopierUrl: "https://www.shopier.com/alnigamestudios/41625102",
        badge: null,
        description: "Yarı otomatik kafe menü yönetim sistemi",
        fullDescription: "Ürünümüz satın alındığında sizlere bir adet editör paketi teslim edilir. Editör paketi sizlere sitenizi istediğiniz gibi tasarlamaya ve yayınlamaya olanak sağlar. Fiyat güncellemeleri standart sürümde mevcut değildir. Fiyat güncellemesi için yeni site oluşturulması gerekmektedir. Eğer fiyatlarınızı aynı site üzerinden güncellemek isterseniz sayfamızdan pro sürümünü satın alabilirsiniz.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_521281ebb085123f8f858f634d3047a2.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 9,
        shopierProductId: "41624953",
        name: "Kafe Menü Sistemi Pro",
        price: 420,
        category: "isletme",
        shopierUrl: "https://www.shopier.com/alnigamestudios/41624953",
        badge: "Pro",
        description: "Tam otomatik profesyonel kafe menü sistemi",
        fullDescription: "Ürünü satın aldığınızda sizler için sistemimizden kafeniz adına bir hesap oluşturulacaktır ve ardından editör paketimiz sizlere mail adresiniz aracılığıyla iletilecektir. Editör paketimiz sizlere sitenizi dilediğiniz gibi tasarlamanızı, düzenlemenizi ve yayınlamanızı sağlar ve herhangi bir ek ücret ödemek zorunda kalmazsınız. Ayrıca pro sürümüne sahip olan müşterilerimiz fiyatlarını verilen kullanıcı adı ve şifre üzerinden daima güncelleyebilirler. Sipariş notu kısmına kafe adınızı ve hangi şehirde olduğunuzu not düşmeniz yeterlidir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_320bdf2684c173268f33dd40ea3d020d.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 10,
        shopierProductId: "40727137",
        name: "Yıl Dönümü Hediyesi Anı Sarmalı",
        price: 200,
        category: "ozelgun",
        shopierUrl: "https://www.shopier.com/alnigamestudios/40727137",
        badge: null,
        description: "Yıl dönümünüze özel anı sunumu",
        fullDescription: "Anı sarmalı ile birlikte ne kadar vakit geçirdiğinizi öğrenin. Güzel fotoğraflar ve metinlerle birlikte geçirdiğiniz anıların bir özeti olsun. Tüm metinler ve fotoğraflar özelleştirilebilirdir. Özelleştirmek istediklerinizi satıcıya not bırak kısmına yazabilirsiniz.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_25412b0576dbf69a74528e45997ca29c.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 11,
        shopierProductId: "40726443",
        name: "Özür Dilerim",
        price: 110,
        category: "ozelgun",
        shopierUrl: "https://www.shopier.com/alnigamestudios/40726443",
        badge: null,
        description: "Duygusal özür dileme sayfası",
        fullDescription: "Özür metni kalpli desenler ve şirin giflerle donatılmıştır. Dilediğiniz özelleştirmeleri not kısmına ekleyiniz. Kişiye özel bir mesajla çok daha anlamlı bir özür dileme deneyimi yaşatın.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_8ef3278f7365da93cef14e7f215aef70.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 12,
        shopierProductId: "40726374",
        name: "Love Calculator",
        price: 40,
        category: "eglence",
        shopierUrl: "https://www.shopier.com/alnigamestudios/40726374",
        badge: "En Uygun",
        description: "Eğlenceli aşk hesaplayıcı",
        fullDescription: "Aşkınızı hesaplayın! Eğlenceli bir şekilde aşk yüzdenizi öğrenin. Kişiye özel isimler ve özel mesajlar eklenebilir. Basit ve eğlenceli bir dijital hediye.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_b365f4ce8e174c44566c2828a5b76fef.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 13,
        shopierProductId: "40726313",
        name: "Gül Bahçesi - 12 Adet",
        price: 65,
        category: "romantik",
        shopierUrl: "https://www.shopier.com/alnigamestudios/40726313",
        badge: null,
        description: "Dijital gül bahçesi animasyonu",
        fullDescription: "Gül bahçesi ürünümüzde her gül toplandığında belirli bir mesaj iletilmektedir. Toplamda 12 adet gül ve 12 adet mesaj bulunmaktadır. Her güle özel bir mesaj yazabilir, sevdiklerinize romantik bir sürpriz yapabilirsiniz.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_54a597a21f793116cbe9f453fab03157.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 14,
        shopierProductId: "40726222",
        name: "Date Daveti - WhatsApp Mesajlı",
        price: 100,
        category: "sevgililer",
        shopierUrl: "https://www.shopier.com/alnigamestudios/40726222",
        badge: null,
        description: "WhatsApp entegreli date daveti",
        fullDescription: "Date davetimiz oldukça basit kullanımdır. İçerisindeki metinler ve etkinlikler kişiye özel özelleştirilebilir. Özelleştirmek istediklerinizi not kısmına yazınız. WhatsApp üzerinden kolayca paylaşabilirsiniz.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_b081b83f367e5f6344c659bb20f0f144.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 15,
        shopierProductId: "40724932",
        name: "Benimle Çıkar Mısın?",
        price: 110,
        category: "sevgililer",
        shopierUrl: "https://www.shopier.com/alnigamestudios/40724932",
        badge: null,
        description: "Romantik çıkma teklifi sayfası",
        fullDescription: "Benimle çıkar mısın adlı üründe evet veya hayır seçeneklerimiz bulunmaktadır. Hayır seçeneği seçildiğinde kullanıcıya evet butonu büyütülerek ısrar edilmektedir. GİF'lerle şekillendirilmiş ve tatlı bir görüntü elde edilmiştir. Kişiye göre metinlerde değişiklik yapılabilmektedir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_b37ba9973b6713467b5c8ec5ae32c561.png",
        deliveryType: "Dijital teslimat"
    },
    {
        id: 16,
        shopierProductId: "43908249",
        name: "Sevgililer Günü - Buluşma Daveti",
        price: 160,
        category: "sevgililer",
        shopierUrl: "https://www.shopier.com/alnigamestudios/43908249",
        badge: "Yeni",
        description: "WhatsApp eklentili buluşma daveti",
        fullDescription: "Sevgililer Günü Buluşma Daveti ile özel gününüzde romantik bir davet gönderebilirsiniz. WhatsApp eklentisi sayesinde kolayca paylaşabilirsiniz. Tarih, saat ve buluşma yeri gibi detayları kişiselleştirebilirsiniz. Sipariş notuna isteklerinizi yazmanız yeterlidir.",
        inStock: true,
        image: "https://cdn.shopier.app/pictures_large/alnigamestudios_63eb1c5bc81428f4ce6684852be6106a.png",
        deliveryType: "Dijital teslimat"
    }
];

// Kategori tanımları
const categories = [
    { id: "all", name: "Tüm Ürünler", icon: "🎁" },
    { id: "sevgililer", name: "Sevgililer Günü", icon: "💕" },
    { id: "tema", name: "Temalı Hediyeler", icon: "🎬" },
    { id: "eglence", name: "Eğlence", icon: "🎮" },
    { id: "ozelgun", name: "Özel Günler", icon: "🎂" },
    { id: "romantik", name: "Romantik", icon: "🌹" },
    { id: "surpriz", name: "Sürpriz", icon: "🎁" },
    { id: "isletme", name: "İşletme", icon: "☕" }
];
